Colorable blush, emoticons, and fluids
Ben987/Bondage-College pull request #1311
Opened 2020-08-20 07:16 UTC by ADRCorp

2020-08-20 20:59 UTC, ace-1331 commented
This PR creates a hole in the items list since there is a non-customizable expression between the Pussy and Blush, the expression groups should be re-ordered properly to fix that.

2020-08-20 23:18 UTC, ADRCorp commented
I noticed that hole but kinda liked it. It actually makes it easier to recognize the new trio. 
In general, if it wasn't a bother to handle, I would actually add "holes" in the appearance menu just so it is easier to find stuff there, so I kinda welcome it XD

The none-customizable thing is the eyebrows, which for some reason never are responsive to colors (probably no one bothered gray-scaling them), if that info helps.

2020-08-28 02:01 UTC, Ben987 commented
This one creates a conflict with other change requests, can you validate?  And yes, you can move the sections to the very end to prevent creating holes in the character appearance screen.  Thanks!

2020-08-29 20:20 UTC, ADRCorp commented
Fixed. Sorry for my horrible response time XD

2020-09-08 04:06 UTC, ace-1331 requested changes
Besides my one comment, everything else looks good.

2020-09-08 04:06 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +		Group: "Hands",
The hands group is duplicated in this PR, I assume this was a merge conflict?
The one coming from Nina's inherit color PR should be kept.

2020-09-08 12:24 UTC, elliesec commented
Nothing to add on top of Ace's comments. Happy to approve once those have been addressed.

2020-09-08 18:07 UTC, ADRCorp commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +		Group: "Hands",
I am pretty sure I moved the hands together with the eyebrows to be below the blush, emoticons and fluids, to prevent creating a gap on the hands slot now that they become uncolorable and thus invisible in the menu. Not sure how they bounced back to their original spot.

2020-09-08 18:27 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +		Group: "Hands",
Yes, re-ordering the group is required to prevent causing holes we've discussed, but the hands group is present on line 876 and line 937.

One of them needs to be deleted. The new one with "InheritColor" needs to be kept, then moved below as you've done with the old group to avoid creating the hole mentioned above.

2020-09-08 20:22 UTC, ADRCorp commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +		Group: "Hands",
Done. Hopefully this will do. Sorry for my slow reaction time...

2020-09-08 20:30 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +		Group: "Hands",
yes, good for the hand. I just checked again as a final test -> the head also needs to be moved under (back then it didn't exist as a group). Sorry, didn't notice it till now.

And no worry about the reaction time, we're approving all PRs and doing merge in the most optimal order afterwards so there's no hurry. It'll happen sometimes this week

2020-09-08 20:54 UTC, ace-1331 approved these changes

2020-09-08 21:10 UTC, elliesec approved these changes

2020-09-12 01:16 UTC, merged