Extended Items Conversion
Ben987/Bondage-College pull request #1326
Opened 2020-08-23 21:18 UTC by Nina-1474

A bug was raised recently where reverse-suspension and ziptie frogtie could both be applied causing the player to be kneeling upside-down. This turned out to be because the item's script wasn't checking the Frogtie's prerequisites properly. Examination of other similar items showed similar incorrect copy-pasted versions, along with other inconsistencies such as where to display the requirement message.
Rather than correct these details, I've changed the items to use the standed ExtendedItem scripts which achieves the same thing. The extended script has a small change to support the Prerequisites settings without needing custom Validate functions that all do the same thing.
I tested each item and didn't find any issues or changes in behaviour other than the intended fixes.

2020-09-08 03:18 UTC, ace-1331 requested changes

2020-09-08 03:18 UTC, ace-1331 commented on BondageClub/Screens/Inventory/ItemPelvis/HempRope/HempRope.js
> +function InventoryItemFeetHempRopeNpcDialog(C, Option) {
The name of the function here does not refer to the correct item.

2020-09-08 03:18 UTC, ace-1331 commented on BondageClub/Screens/Inventory/ItemLegs/HempRope/HempRope.js
> +function InventoryItemFeetHempRopeNpcDialog(C, Option) {
Same here, the name of the function is not the right one

2020-09-08 08:55 UTC, ace-1331 approved these changes

2020-09-08 08:57 UTC, ace-1331 commented
Sorry for the commits, I was testing a few things among what we can do right now. Looks like we can fix small mistakes like these then push to the branch without merging when appropriate to save some time.

This should help to prevent delays when handling PRs due to merge conflicts and such.
All looks good to me now!

2020-09-08 08:57 UTC, ace-1331 approved these changes

2020-09-08 14:06 UTC, elliesec approved these changes
Yep, all looks good to me!

2020-09-09 20:18 UTC, elliesec commented
Well this got a whole lot smaller 😅

2020-09-09 20:18 UTC, merged