Bed Items
Ben987/Bondage-College pull request #1375
Opened 2020-09-07 01:36 UTC by Ayesha-678

New bed Assets (credit to Gnarp for those!)
Wrapped blanket bindings
Blanket Hood

2020-09-13 20:27 UTC, ace-1331 commented
After merging #1336, I'm going through PRs to check what might conflict/be missing.

When you resolve the conflicts, please make sure the items retain the proper SetPose/AllowPose/AllowActivePose, etc. set in 1336 as it appears this PR might change some of the same lines for the bed in particular.

2020-09-14 15:07 UTC, Ayesha-678 commented
Should be fixed.

2020-09-14 17:10 UTC, ace-1331 requested changes

2020-09-14 17:10 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "DisplayCase", Fetish: ["Metal"], Value: 60, Difficulty: -2, SelfBondage: 1, Time: 15, RemoveTime: 10, AllowLock: true, Prerequisite: ["NotSuspended"], Effect: ["Prone", "Enclose", "DeafLi
Some of these item devices are losing their Audio, SetPose, etc. after the merge

2020-09-15 14:13 UTC, Ayesha-678 commented
Should be fixed again, i hope!

2020-09-19 12:25 UTC, elliesec requested changes
Mostly looks good to me! Only two points:
* Audio entries still appear to be missing for some of the devices
* The assets/CSV entries for the blanket hood all appear to be in place, but there doesn't appear to be an entry for it in `Female3DCG.js`

2020-09-19 12:25 UTC, elliesec commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "DisplayCase", Fetish: ["Metal"], Value: 60, Difficulty: -2, SelfBondage: 1, Time: 15, RemoveTime: 10, AllowLock: true, Prerequisite: ["NotSuspended"], Effect: ["Prone", "Enclose", "DeafLi
Looks like a bunch of the devices are still missing audio entries

2020-09-22 17:50 UTC, Ayesha-678 commented
i think i messed this up too badly >.< I'll have to remake it, starting with the new bed assets.

2020-09-22 17:50 UTC, closed without merging