Fix: Typo fix for ear phones
Ben987/Bondage-College pull request #1390
Opened 2020-09-10 09:46 UTC by SandrineBC

# Summary
In `Dialog_Player.csv` the AssetName attribute was used, resulting in an output of 'headphoneearplugs'.
This PR replaces the AssetName with the correct text.

2020-09-10 09:52 UTC, elliesec requested changes
Rather than change the CSV, you should be able to change the dictionary value to `DialogFocusItem.Asset.Name` in `HeadphoneEarPlugs.js`, and it should automatically get interpreted into the asset's translated name (or the English version if no translation is available).

2020-09-10 14:14 UTC, elliesec requested changes

2020-09-10 14:14 UTC, elliesec commented on BondageClub/Screens/Inventory/ItemEars/HeadphoneEarPlugs/HeadphoneEarPlugs.js
> +		{ Tag: "AssetName", Text: DialogFocusItem.Asset.Description.toLowerCase() },
This should use `DialogFocusItem.Asset.Name` rather than `DialogFocusItem.Asset.Description.toLowerCase()`, otherwise everyone receives the asset name in whichever language the person changing the volume is using:

![image](https://user-images.githubusercontent.com/62729616/92743017-15778180-f378-11ea-9d3a-98a6e3a40790.png)

2020-09-10 14:18 UTC, elliesec commented on BondageClub/Screens/Inventory/ItemEars/HeadphoneEarPlugs/HeadphoneEarPlugs.js
> +		{ Tag: "AssetName", Text: DialogFocusItem.Asset.Description.toLowerCase() },
And the key should be `AssetName`, rather than `Text` - that makes it get interpreted properly on the receiving end for everyone I believe:
```js
{ Tag: "AssetName", AssetName: DialogFocusItem.Asset.Name }
```

2020-09-10 14:20 UTC, SandrineBC commented on BondageClub/Screens/Inventory/ItemEars/HeadphoneEarPlugs/HeadphoneEarPlugs.js
> +		{ Tag: "AssetName", Text: DialogFocusItem.Asset.Description.toLowerCase() },
Then that was the problem in the first case...

2020-09-10 14:29 UTC, elliesec approved these changes
Looks good to me!

2020-09-10 17:48 UTC, ace-1331 approved these changes

2020-09-11 01:56 UTC, ace-1331 requested changes
The publishaction and npc dialog function need to be added to the Bluetooth earbuds as well (a reference to the headphone's one is enough). (See what I did for the belts as well as the bugfix in #1401 )

2020-09-11 06:11 UTC, ace-1331 approved these changes

2020-09-11 06:11 UTC, merged