Refactor item arms ornate cuffs
Ben987/Bondage-College pull request #1397
Opened 2020-09-10 19:21 UTC by SandrineBC

# Summary
Refactored the arms ornate cuffs to use the extended item script. Filenames were changed and new files added for consistency.

2020-09-10 19:39 UTC, ace-1331 requested changes
Like #1391, has discussed we can keep the old filenames and remove restrain by using the new HasType from #1396

2020-09-13 16:54 UTC, ace-1331 approved these changes

2020-09-13 16:55 UTC, ace-1331 commented
Once #1414 is merged, this will be good to go

2020-09-13 20:35 UTC, ace-1331 commented
These cuffs are subject to the same comment I left on #1391

2020-09-13 23:50 UTC, elliesec approved these changes

2020-09-14 06:23 UTC, merged