Refactor: Strait jacket to extended item
Ben987/Bondage-College pull request #1407
Opened 2020-09-11 10:13 UTC by SandrineBC

# Summary
Refactored the strait jacket to use the extended item script.

2020-09-11 15:45 UTC, ace-1331 requested changes

2020-09-11 15:45 UTC, ace-1331 commented on BondageClub/Scripts/Asset.js
> +		InheritColor: NewAsset.InheritColor,
You're re-adding this line, probably due to a merge conflict

2020-09-11 15:57 UTC, ace-1331 requested changes

2020-09-11 15:57 UTC, ace-1331 commented on BondageClub/Screens/Inventory/ItemArms/StraitJacket/StraitJacket.js
> +	C.CurrentDialog = DialogFind(C, "RoundPiercingNPCReaction" + Option.Name, "ItemNipplesPiercings");
Still using the piercing texts here

2020-09-11 15:57 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "StraitJacket", Fetish: ["Leather"], Value: 150, Difficulty: 6, SelfBondage: 8, Time: 35, RemoveTime: 20, AllowLock: true, DefaultColor: "#A0A0A0", Hide: ["Cloth", "ItemNipplesPiercings"],
Missing allowtypes, so it's not saving properly

2020-09-11 16:38 UTC, SandrineBC commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "StraitJacket", Fetish: ["Leather"], Value: 150, Difficulty: 6, SelfBondage: 8, Time: 35, RemoveTime: 20, AllowLock: true, DefaultColor: "#A0A0A0", Hide: ["Cloth", "ItemNipplesPiercings"],
That AllowTypes issue must have been there for ages...

2020-09-11 16:50 UTC, ace-1331 approved these changes

2020-09-13 20:38 UTC, ace-1331 commented
After merging #1336, I'm going through PRs to check what might conflict/be missing.

When you resolve the conflicts, please make sure the items retain the proper SetPose/AllowPose/AllowActivePose, etc. set in 1336 as it appears this PR might change some of the same lines.

2020-09-14 06:11 UTC, SandrineBC commented
Looks good after the merge

2020-09-14 06:37 UTC, ace-1331 requested changes

2020-09-14 06:37 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "StraitJacket", Value: 150, Difficulty: 6, SelfBondage: 8, Time: 35, RemoveTime: 20, AllowLock: true, DefaultColor: "#A0A0A0", Hide: ["Cloth", "ItemNipplesPiercings"], HideItem: ["ClothLow
I assume removing the fetish was not intended here?

2020-09-14 08:12 UTC, SandrineBC commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "StraitJacket", Value: 150, Difficulty: 6, SelfBondage: 8, Time: 35, RemoveTime: 20, AllowLock: true, DefaultColor: "#A0A0A0", Hide: ["Cloth", "ItemNipplesPiercings"], HideItem: ["ClothLow
In fact it was, as the leather fetish made no sense. We have the leather strait jacket for this fetish, so I removed it on the canvas version. Perhaps we could introduce a 'medical' fetish at one point?

2020-09-14 14:07 UTC, ace-1331 approved these changes

2020-09-14 22:41 UTC, elliesec approved these changes

2020-09-14 23:05 UTC, merged