Refactor: Nipple suction cups to extended items
Ben987/Bondage-College pull request #1439
Opened 2020-09-16 07:00 UTC by SandrineBC

# Summary
This PR refactors the butt pump to use the extended item script and purges a small layout error in the extended item button placement for four options

# Dependencies
This PR needs #1436 for the `ShowImage` option of the extended item dialogs

2020-09-17 17:18 UTC, SandrineBC commented on BondageClub/Screens/Character/Player/Dialog_Player.csv
>  SuctionLevel0,,,Suction Cup level: Loose,,
Yes, that’s on my todo list. Same for the inflatable items.

2020-09-17 17:18 UTC, SandrineBC commented on BondageClub/Screens/Character/Player/Dialog_Player.csv
>  SuctionLevel0,,,Suction Cup level: Loose,,
Yes, that’s on my todo list. Same for the inflatable items.

2020-09-22 21:38 UTC, Nina-1474 approved these changes

2020-09-22 22:45 UTC, elliesec requested changes

2020-09-22 22:45 UTC, elliesec commented on BondageClub/Screens/Character/Player/Dialog_Player.csv
>  SuctionLevel0,,,Suction Cup level: Loose,,
I think now would be a good time to remove those `SuctionLevel<Number>` entries, then I think this is good to go in.

2020-09-23 07:58 UTC, SandrineBC commented on BondageClub/Screens/Character/Player/Dialog_Player.csv
>  SuctionLevel0,,,Suction Cup level: Loose,,
PR #1440 should go in, before. Then this should be the last one...

2020-09-23 19:50 UTC, elliesec approved these changes

2020-09-23 19:52 UTC, merged