Refactor: Bondage bench to extended items
Ben987/Bondage-College pull request #1449
Opened 2020-09-19 07:44 UTC by SandrineBC

# Summary
The PR refactors the bondage bench to use the extended items script. This has the following implications
* Getting rid of `BondageBenchStraps.js`
* Using the new feature of layer priorities for the bench and the straps
* Introducing the new feature to allow the usage of locks on type level, including all checks in the dialog screen and the receivers end. If you want the whole item to be lockable, just add `AllowLock` on the asset level, as usual. Else add `AllowLock` within the properties of the type. 
* The receiving end was modified to accept those locks as well

# Points to discuss
As the prerequisite for a certain type is not defined in the type's properties, we could think about moving the `AllowLock` attribute from the properties to the main entry as well...

2020-09-22 22:17 UTC, Nina-1474 approved these changes
Looks good. One possible suggestion: the "None" option's image used to represent the addition of straps but now it represents the removal of them, so the straps in the image are a bit misdirecting. What about using an edited version of the item's main preview image without straps instead?

2020-09-25 03:08 UTC, ace-1331 submitted a review, later dismissed
Seems to be working as intended and its a good option to have until we figure out layer locks.

It was intended for the crib to be only lockable when closed so it could be possible now.

Just double check my 1 comment when you can

2020-09-25 03:08 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> -				Name: "Covers", Value: -1, Difficulty: 1, SelfBondage: 0, Prerequisite: "OnBed", BuyGroup: "Bed",
Im not sure if its with the recent merge, but Im not sure if the cover layers being changed here is intended?

2020-09-25 05:38 UTC, SandrineBC commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> -				Name: "Covers", Value: -1, Difficulty: 1, SelfBondage: 0, Prerequisite: "OnBed", BuyGroup: "Bed",
Perhaps a merging problem and I changed that back.

2020-09-27 23:40 UTC, Nina-1474 commented
Since the preview images were originally 200 pixel squares rather than the typical 221 pixels, they weren't quite centred. I've adjusted them to correct this, along with making the None image suggestion from above.

2020-09-27 23:41 UTC, Nina-1474 requested changes
Since there are no colourable layers, clicking the colour button hits an error. Both the bench and straps were colourable before so I think they should remain so.

2020-09-28 09:08 UTC, SandrineBC commented
I added the colorization of the layers. It seems, I got your images included, @Nina-1474 , but you better double check.
When I tested, the colorization seemed a bit unstable, Sometimes the picked color was not shown in the icon, sometimes I was not able to colorize the item as a whole. Perhaps there's still a glitch hidden somewhere...

2020-10-09 20:48 UTC, Nina-1474 approved these changes

2020-11-03 19:02 UTC, elliesec approved these changes

2020-11-03 19:02 UTC, merged