New item: wooden sign
Ben987/Bondage-College pull request #1477
Opened 2020-09-25 00:12 UTC by ace-1331

- added a custom sign
- added a few extra bits to increase what can be done with After/Before draw

It fits best in ItemMisc as it has similar properties than the wooden tray.
I can just revert the last commit if you prefer to have it in neck accessories.. however that makes it a lot less usable and slightly awkward with collars.

I changed the login fix to ignore this item.

I added a custom font folder and the font license with it, so we can add custom fonts used with items in that folder (fonts are only loaded when first used)

Thanks to Gnarp for the assets!

2020-09-28 00:37 UTC, Nina-1474 requested changes

2020-09-28 00:37 UTC, Nina-1474 commented on BondageClub/Screens/Inventory/ItemMisc/WoodenSign/WoodenSign.js
> +        Dictionary.push({ Tag: "DestinationCharacterName", Text: C.Name, MemberNumber: C.MemberNumber });
Should this be TargetCharacterName?

2020-09-28 01:53 UTC, ace-1331 commented
Indeed, fixed it.

2020-09-28 02:07 UTC, Nina-1474 approved these changes
I'd possibly suggest having a label/text to the left of the input boxes saying something like "First Line:" & "Second Line:". Though it's pretty obvious that's how it works after trying it once so not a big deal. Overall looks great!

2020-09-28 02:13 UTC, Nina-1474 requested changes
Just noticed this reinserts some lines into LayerNames.csv that had been removed under #1464.

2020-09-28 02:38 UTC, ace-1331 commented
fixed

2020-09-28 02:39 UTC, Nina-1474 approved these changes

2020-10-09 17:01 UTC, elliesec approved these changes

2020-10-09 17:01 UTC, merged