Change: Custom tag to use multi color system
Ben987/Bondage-College pull request #1478
Opened 2020-09-25 16:48 UTC by ace-1331

- moved the text color to its own layer for simplicity

Since multicolor wasnt a thing when I made it, decided to improve it now rather than later.

requires #1477 for a small change to commondraw

2020-09-28 00:41 UTC, Nina-1474 requested changes
The default gold colour is initially applied to both the tag and text, making it very hard to read. I'd say it would be better to have the text default to black.

2020-09-28 01:58 UTC, ace-1331 commented
good point, just updated it

2020-09-28 02:09 UTC, Nina-1474 approved these changes

2020-10-09 17:06 UTC, elliesec approved these changes

2020-10-09 17:07 UTC, merged