Rope and Chains Refactor
Ben987/Bondage-College pull request #1493
Opened 2020-09-26 19:19 UTC by Nina-1474

I had originally planned on covering the refactoring of Hemp Rope and Chains for ItemArms under the suspension height feature, along with the necessary ExtendedItem enhancement. However since there's a fair chance it won't get done by the next release, I'm doing a straight refactor now.
This includes the missing details for the multi-colouring. Also since layers named "" are changed to null by the time they're used as keys in the multi-colour code, it looks for entries like ItemArmsHempRopenull. This has small tweaks so the type porten is blank rather than 'null', i.e. ItemArmsHempRope, for consistency.

2020-09-27 03:02 UTC, ace-1331 requested changes

2020-09-28 02:22 UTC, Nina-1474 commented on BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
> +		{ Tag: "DestinationCharacter", Text: C.Name, MemberNumber: C.MemberNumber },
Fixed!

2020-09-28 02:37 UTC, ace-1331 approved these changes

2020-09-30 19:13 UTC, elliesec reviewed
Looks good. I'm going to merge #1504 first, so will hold off on the approval until this has been updated.

2020-09-30 19:47 UTC, elliesec approved these changes

2020-09-30 19:47 UTC, merged