Optimize Drawing.js
Ben987/Bondage-College pull request #1507
Opened 2020-09-29 21:25 UTC by NoneNoname

2021-01-27 17:16 UTC, elliesec reviewed
One suggestion, one question. But otherwise, looks like a nice set of optimisations.

2021-01-27 17:16 UTC, elliesec commented on BondageClub/Scripts/Drawing.js
> +			const MainCanvasRect = document.getElementById("MainCanvas").getBoundingClientRect();
Might be a little neater if you shifted this and the chunk on line 1058 out after the if/else, and just define a scale value (`2000 / W` or `1000 / H`) inside here.

2021-01-27 17:16 UTC, elliesec commented on BondageClub/Scripts/Drawing.js
> +	setTimeout(DrawWindowResize, 1000);
Why are the deferred calls to `DrawWindowResize` needed?

2021-01-27 22:03 UTC, NoneNoname commented on BondageClub/Scripts/Drawing.js
> +	setTimeout(DrawWindowResize, 1000);
previously this was called every DrawProcess, and now only on resize, when the window loads the size can be incorrect, actually on mobile I did experience this effect even more and few extra deferred calls were necessary:
```
	DrawWindowResize();
	setTimeout(DrawWindowResize, 1000);
	setTimeout(DrawWindowResize, 3000);
	setTimeout(DrawWindowResize, 5000);
	if (CommonIsMobile) setTimeout(DrawWindowResize, 10000);
```

2021-01-27 22:20 UTC, elliesec commented on BondageClub/Scripts/Drawing.js
> +	setTimeout(DrawWindowResize, 1000);
It seems odd that it's not getting called as a result of the resize event listener of it's not accurate the first time - presumably there's some underlying cause to that? In any case, it might be worth adding a comment over these to explain what they're there for.

2021-01-27 22:38 UTC, elliesec commented on BondageClub/Scripts/Drawing.js
> +						const max_time = 5000 // 5 seconds
Changing this to a `const` has exposed an issue in the existing code: `max_time` only gets defined in the `if` - the drawing then proceeds regardless. This `if` needs braces.

2021-01-27 22:41 UTC, elliesec commented on BondageClub/Scripts/Drawing.js
>  	if (Invert) Img = DrawInvertImage(Img);
This line is now re-assigning a `const` - should be a `let` now.

2021-01-27 22:42 UTC, elliesec commented on BondageClub/Scripts/Drawing.js
>  	if (Invert) Img = DrawInvertImage(Img);
This line is now re-assigning a `const` - should be a `let` now.

2021-01-27 23:01 UTC, NoneNoname commented on BondageClub/Scripts/Drawing.js
> +	setTimeout(DrawWindowResize, 1000);
resize is only the result of the window being resized and not the content change so that may cause this but I am not too sure the exact reason for this, probably there is a better solution I just yet to find it

also, it may seem fine at first to leave the deferred calls out, but in some cases, it will result (especially on mobile) the canvas getting oversized

2021-01-27 23:13 UTC, elliesec commented on BondageClub/Scripts/Drawing.js
> +	setTimeout(DrawWindowResize, 1000);
Yeah, leaving them in is fine for now, although it would be good to try to identify the cause at some point. Like I said, I'd be inclined to just leave a comment above the code to explain why it's there, and maybe someone will figure it out in the future.

2021-01-27 23:41 UTC, NoneNoname commented on BondageClub/Scripts/Drawing.js
> +	setTimeout(DrawWindowResize, 1000);
added the comment for it

2021-01-28 00:05 UTC, elliesec commented
Looks good to me now. I'll pull down the latest changes and give it another test run tomorrow just to double check.

2021-01-28 14:39 UTC, jomshir98 requested changes
Two small notes, but otherwise LGTM

2021-01-28 14:39 UTC, jomshir98 commented on BondageClub/Scripts/Drawing.js
> +	if (MainCanvas.measureText(Text).width > Width) return;
This logic seems inverted to me

```suggestion
	if (MainCanvas.measureText(Text).width <= Width) return;
```

2021-01-28 14:39 UTC, jomshir98 commented on BondageClub/Scripts/Drawing.js
> +		Touch = function Touch(event) {
`Touch` is a name of global interface we are overwriting; maybe worth renaming it to something else?

2021-01-28 16:59 UTC, jomshir98 approved these changes

2021-01-28 20:50 UTC, elliesec approved these changes
Looks good to me - no obvious issues that I can see, and everything seems to work well in testing. Good call shifting the canvas resize out into CSS. Happy for this to go in.

2021-02-03 23:28 UTC, Nina-1474 approved these changes

2021-02-04 13:14 UTC, Nina-1474 commented on BondageClub/Scripts/Drawing.js
> +		Canvas.drawImage(TempCanvas.canvas, X, Y);
Won't this line result in the image being drawn twice, once without the opacity setting and once with it?

2021-02-04 13:32 UTC, NoneNoname commented on BondageClub/Scripts/Drawing.js
> +		Canvas.drawImage(TempCanvas.canvas, X, Y);
Yep it will, I fixed it, now it should work well

2021-02-04 13:55 UTC, merged