Futuristic Panel Gag
Ben987/Bondage-College pull request #1520
Opened 2020-10-04 16:45 UTC by Ada18980

- Added a new futuristic gag with three modes providing varying levels of gag strength. It can't be modified while locked.

Tested:

- Trying to modify while locked
- Trying to modify while bound
- Trying to modify while bound and locked
- Maid removal
- Multi color picker
- Verified strings in English

2020-10-04 19:34 UTC, Ada18980 commented
I realized that the localization may be broken, I did not localize any of the strings.

2020-10-04 19:49 UTC, ace-1331 commented
> I did not localize any of the strings. Is this going to cause crashes for other language users or is it only an accessibility issue?

It will default to English when a line is not translated, so no it won't cause any crash

2020-10-04 20:34 UTC, ace-1331 requested changes
Besides the 3 code comments below, my main comment is the following ->
I can't swap from ball to plug mode, I always have to go back to padded first, is this intended?

2020-10-04 20:34 UTC, ace-1331 commented on BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/FuturisticHarnessPanelGag.js
> +			Effect: ["GagLight"],
This should have the blockmouth effect as well, otherwise it means anything that requires the mouth to be open will be possible such as the penetrate action.

2020-10-04 20:34 UTC, ace-1331 commented on BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
> +
Since the second file is exactly the same, the functions should just point to the other gag's functions to reduce code duplication and make these items easier to maintain

2020-10-04 20:34 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.csv
> +ItemMouth,FuturisticHarnessPanelGag,Futuristic Panel Gag w/ Harness
Can you change "w/" for "with"? Or "Futuristic Harness Panel Gag" is shorter if you want to save room

2020-10-04 22:19 UTC, Ada18980 reviewed
Hi Ace,

I agree with your 3 code commends and have committed them to the repo. Re: the inability to switch, I'm not sure why this is happening as I did not intentionally set that to happen.

2020-10-04 22:19 UTC, Ada18980 commented on BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/FuturisticHarnessPanelGag.js
> +			Effect: ["GagLight"],
Agreed, I made the change.

2020-10-04 22:19 UTC, Ada18980 commented on BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
> +
Done.

2020-10-04 22:40 UTC, Ada18980 commented
There, the issue that was preventing the user from switching from Ball to Plug was the fact that both were of "Plug" type whereas they should have been different

2020-10-04 23:12 UTC, ace-1331 approved these changes

2020-10-06 02:21 UTC, Ada18980 commented
Double checked that the gag still works on the new commit.
@Ben987

2020-10-06 15:05 UTC, merged