Interactive Visor
Ben987/Bondage-College pull request #1532
Opened 2020-10-06 22:01 UTC by Ada18980

Added a blindfold version of EmilyR's futuristic visor, complete with locking symbol and transparent/blind types. Has 4 levels:
- Transparent
- Light tint
- Heavy tint
- Blind

Tested chat messages, ability to modify while locked (the user intentionally has to have access to change the type, since it's all supposed to be software), and graphics of all 4 types (including lock symbol)

2020-10-07 01:32 UTC, ace-1331 requested changes
Besides the code comments, the rest looks good.

2020-10-07 01:32 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +					{ Name: "Mask", AllowColorize: true },
Any reason why there is a single layer? It's not necessary, the layer can be removed to simplify the code

2020-10-07 01:32 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "InteractiveVisor", Fetish: ["Metal"], BuyGroup: "FuturisticVisor", Value: 50, Time: 5, AllowLock: true, Hide: ["ItemNoseNoseRing", "MaskFuturisticVisor"], Effect: ["Prone"], AllowEffect:
There's an extra allowtype that should be removed (`"Face"`)

2020-10-07 05:13 UTC, Ada18980 commented
Resolved both issues and re-tested.

2020-10-07 16:44 UTC, ace-1331 approved these changes

2020-10-09 05:43 UTC, Ben987 commented
Absolutely!  I will include it in the next beta, thanks :)

2020-10-09 05:43 UTC, merged