EmilyR's PR
Ben987/Bondage-College pull request #1533
Opened 2020-10-07 03:19 UTC by EmilyR42

2 backgrounds, 4 clothes, yanked one background I meant to ditch earlier.

2020-10-07 16:43 UTC, ace-1331 requested changes
Beside the 1 comment I left, the tails +/- appear to be behind the cape, Im not sure if it is intended or if there is a better way to do it  so either way is fine with me.

I saw Ben added `Random: false` to some of the newer "non-traditional" items, I'd recommend doing the same for the cape.

2020-10-07 16:43 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "BondageBustier1", BuyGroup: "BondageDress1", Value: -1, HideItem: ["ItemNipplesPiercingsRoundPiercing", "ItemNipplesPiercingsWeightedPiercing", "ItemNipplesLactationPump"] },
These items do not have their corresponding previews (BondageBustier1/BondageBustier2)

2020-10-07 22:16 UTC, ace-1331 approved these changes

2020-10-08 11:47 UTC, gatetrek approved these changes
A small suggestion about the panties, how about calling the latex panties1 crotchless and number2 basic,  latex panties?

2020-10-08 16:12 UTC, merged