Small coffin fix, and cryo capsule.
Ben987/Bondage-College pull request #1553
Opened 2020-10-11 21:49 UTC by aldarris

Coffin was erasing the emoticon, and another alfa mask was required to cut off certain kinds of hair.
Cryo capsule is practically cut and paste.

2020-10-11 21:59 UTC, ace-1331 commented on BondageClub/Screens/Character/Player/Dialog_Player.csv
> +CoffinSetOpen,,,SourceCharacter opens the lid on the coffin TargetCharacter is in.,,
There's a mismatch between the text and what's passed in the dictionnary (TargetCharacterName vs TargetCharacter)

Target character outputs "X closes the lid on the CryoCapsule herself is in" so it is not correct anyway.

Might want to look at the action text to have them reflect what you intend to say.

2020-10-11 22:00 UTC, ace-1331 requested changes
Other than the 1 comment about the actions, everything else looks good

2020-10-11 22:04 UTC, aldarris commented
TargetCharacter instead of TargetCharacterName is the fix.  In the current beta, it prints 'TargetCharacterName' to the chat isntead of target character's name.

2020-10-11 22:19 UTC, aldarris commented
Oh, I see.  The 'TargetCharacter' has to match in js file as well.
Fixed.

2020-10-11 22:51 UTC, ace-1331 commented
I was just saying "(X opens the lid on the cryogenic capsule **herself** is in.)" doesn't sound right like 
"(X opens the lid on the cryogenic capsule **she** is in.)" or like most items do, "(Gray opens the lid on her cryogenic capsule.)"

But I'm not a native english speaker so I'll leave that up to everyone else.
However, I noticed another thing, the lower Alpha mask on the capsule visually cuts the feet off in its open state because it goes a little lower than the coffin. It could probably be lowers a bit more to look better.

2020-10-11 23:25 UTC, aldarris commented
Fixed the cutout (it was frame as well as alpha).
Looked over the ChatRoomMessage function, no idea how to replace 'herself' with 'she'.  Not without some major refactoring.

2020-10-12 00:03 UTC, aldarris commented
Grammar is fixed.

2020-10-12 00:41 UTC, ace-1331 approved these changes

2020-10-21 04:59 UTC, Ben987 commented
Sweet!  This will fit well with all the new sci-fi stuff.  Thanks a lot :)

2020-10-21 04:59 UTC, merged