Add support for MU* style poses
Ben987/Bondage-College pull request #2591
Opened 2021-06-18 10:26 UTC by tuxyq

This adds : as a synonym for * and /me for MUD/MUSH users
It also avoids obvious smileys

Posting in this state to gauge if this is something you'd accept, one improvement I'm considering is making it a toggle in the settings as well.

![https://i.imgur.com/FvnkFzO.gif](https://i.imgur.com/FvnkFzO.gif)

2021-06-18 10:59 UTC, TessaTech commented
Yet another synonym for * and /me sounds a bit odd. I'm all for making things individualizable for users but if we add this now we might just as well add other emote formats that are used somewhere else.
I would suggest to at least make this configurable before merging it since most users are used to * or /me and using up a commonly used character like : all of a sudden could annoy some people.

Also there are much more emoticons that start with : and considering them all would making relying on : for general text emotes nothing one would want to get used to.

Like:
> :jumps jumps forward -> _*Tessa jumps forward*_
> :pounces forward ->**Tessa: :pounces forward**

2021-06-18 11:05 UTC, TessaTech requested changes
I think the conversion doesn't quite match up here.

2021-06-18 11:05 UTC, TessaTech commented on BondageClub/Screens/Online/ChatRoom/ChatRoom.js
> +];
Either this would have to turn all the lower care letters to upper case...

2021-06-18 11:05 UTC, TessaTech commented on BondageClub/Screens/Online/ChatRoom/ChatRoom.js
> +		} else if ((m.indexOf("*") == 0) || (m.indexOf("/me ") == 0) || (m.indexOf("/action ") == 0) || (m.indexOf(":") == 0 && (m.indexOf("'s") == 1 || !ChatMuPoseIgnoreCharacters.includes(m[1].toUpperCas
...or this would have to convert the tested letter to lower case
`!ChatMuPoseIgnoreCharacters.includes(m[1].toLowerCase())`

2021-06-18 11:07 UTC, tuxyq commented
Good point regarding that last part.

I opened this PR to get feedback before I sink time into expanding it into being configurable, if this is a feature that would potentially be accepted, that would be something I'd be looking into.

Current state is the POC

2021-06-18 11:09 UTC, tuxyq commented on BondageClub/Screens/Online/ChatRoom/ChatRoom.js
> +		} else if ((m.indexOf("*") == 0) || (m.indexOf("/me ") == 0) || (m.indexOf("/action ") == 0) || (m.indexOf(":") == 0 && (m.indexOf("'s") == 1 || !ChatMuPoseIgnoreCharacters.includes(m[1].toUpperCas
yeah, I swapped things around and neglected that I had lowercase in the array :)

2021-06-18 11:25 UTC, TessaTech commented
Also another few common smileys that wouldn't be catched by this:
:3, :o, :v, :x, :F
And i'm sure there could be found even more if one searches more thoroughly.

2021-06-18 11:29 UTC, TessaTech commented
I'd suggest asking around among the player base and on the discord in the "suggestions" or "work in progress" channels for oppinion.

2021-06-18 19:20 UTC, tuxyq commented
Updated how it decides if it parsing the emote, it's more naive, but also a faster method, I can't think of a case where you have a 3 letter emote, hence making it that naive.

2021-06-19 19:43 UTC, tuxyq commented
noticed that #1462 will conflict with my changes when/if it's merged, if/when that happens, Ill refactor this to match

2021-06-19 21:27 UTC, Nina-1474 reviewed
Having : as both a divider in the help message and part of a comment makes it a little hard to read. Plus there's an extra comma in there. I'd suggest something like this which puts the extra option in parentheses after the normal options.

2021-06-19 21:27 UTC, Nina-1474 commented on BondageClub/Screens/Character/Player/Dialog_Player.csv
> +ChatRoomHelp,,,"Commands available : /help : show this help text, :(if enabled in settings), * or /me : write an emote, ** or /action : write an action, click on someone's name on the left to whisper
```suggestion
ChatRoomHelp,,,"Commands available : /help : show this help text, * or /me (or : if enabled in settings) : write an emote, ** or /action : write an action, click on someone's name on the left to whisper, PgUp/PgDn keys to navigate chat input history, /coin : flip a coin, /dice Y or XdY : roll X dice with Y-sides (from 2 to 100 sides), /afk, /friendlistadd [ID], /friendlistremove [ID], /whitelistadd [ID], /whitelistremove [ID], /blacklistadd [ID], /blacklistremove [ID], /ghostadd [ID], /ghostremove [ID], /kick [ID], /ban [ID], /unban [ID], /promote [ID], /demote [ID]",,
```

2021-06-25 19:12 UTC, Ben987 commented
Sure!  I've never used : for emotes but if some players are used to that and there's a setting, it should be good.  Thanks :)

2021-06-25 19:12 UTC, merged

2021-06-27 02:21 UTC, kimei-nishimura commented
FYI: 3-char smilies that I have seen used would be like :-) or :-D or :^) (though recognizing these may be an indicator of how long I've been on the internet rather than common usage).

2021-06-27 16:14 UTC, tuxyq commented
That was considered with the last change for a more naïve approach, it only acts if the message is longer than 3 characters long, 4 character smileys are uncommon, and 3 letter and fewer emotes are rare, hence the naïve approach