Advanced Vibrator Modes Disable
Ben987/Bondage-College pull request #2610
Opened 2021-06-23 06:55 UTC by Ada18980

Allows the player (if appearance is below Extreme) to block advanced vibrator modes in the arousal menu. If the player is extreme, it is forced off (because the player cannot block any items or types).

Also adds validation to prevent trolling.

2021-06-23 08:11 UTC, elliesec requested changes

2021-06-23 08:11 UTC, elliesec commented on BondageClub/Scripts/Validation.js
> +	if (property && typeof property.Mode === "string" && Player.ArousalSettings && Player.ArousalSettings.DisableAdvancedVibes) {
The `property` check here shouldn't be needed - `property` is guaranteed to be an object due to the earlier checks.

As this function can be called on characters that aren't the player, we shouldn't be directly referencing `Player` here, we should be using `C` instead.

Also... as this is just checking whether or not `Property.Mode` is a string, won't this end up _always_ triggering a sanitization, even for basic vibrator modes?

2021-06-23 08:11 UTC, elliesec commented on BondageClub/Scripts/VibratorMode.js
> +			var Color = Property.Mode === Option.Property.Mode ? "#888" : (!(OptionName == VibratorModeSet.ADVANCED && CurrentCharacter.ArousalSettings && CurrentCharacter.ArousalSettings.DisableAdvancedVibes
Probably best to assign `CharacterGetCurrent()` to a variable here, and then use that instead of using `CurrentCharacter` directly. Similarly below.

2021-06-23 08:18 UTC, Ada18980 commented on BondageClub/Scripts/Validation.js
> +	if (property && typeof property.Mode === "string" && Player.ArousalSettings && Player.ArousalSettings.DisableAdvancedVibes) {
Dang, I shouldn't be coding this late at night. Will submit a fix

2021-06-23 08:19 UTC, Ada18980 commented on BondageClub/Scripts/VibratorMode.js
> +			var Color = Property.Mode === Option.Property.Mode ? "#888" : (!(OptionName == VibratorModeSet.ADVANCED && CurrentCharacter.ArousalSettings && CurrentCharacter.ArousalSettings.DisableAdvancedVibes
Ill do that, thanks

2021-06-23 17:19 UTC, elliesec approved these changes

2021-06-25 17:24 UTC, Ben987 commented
Alright!  Thanks for that new preference.

2021-06-25 17:24 UTC, merged