New fur items
Ben987/Bondage-College pull request #2674
Opened 2021-07-03 02:34 UTC by DualityIncarnate

Added fur headband and fur scarf

2021-07-03 02:54 UTC, ace-1331 requested changes
- Missing asset in suspsension pose for the FurHeadBand
- The hiddenitem labels should be HatFurHeadBand

(For context, I'm currently speaking with them since it's a first contribution, posting this review here as I just wanted to make sure this is not getting merged ahead of time)

2021-07-03 03:06 UTC, ace-1331 submitted a review, later dismissed

2021-07-03 03:10 UTC, ace-1331 approved these changes
all good now

2021-07-05 15:20 UTC, Ben987 commented
Absolutely!  Thanks for these new items :)

2021-07-05 15:20 UTC, merged