New Item: Doll Box
Ben987/Bondage-College pull request #2887
Opened 2021-09-04 11:44 UTC by Shiranui-Izayoi

- Added a tutu skirt
   - Added a new font

All credit goes to Titania for the assets (@QueenTita), I just did the coding. Added a new font for the boxes text. If it is to hard to read let me know and I can change it to something else. The font was used on request from Titania.

2021-09-04 20:25 UTC, ace-1331 requested changes

2021-09-04 20:25 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "DollBox", Priority: 58, Fetish: ["Metal"], Value: 20, Difficulty: -2, SelfBondage: 1, Time: 1, RemoveTime: 1, Left: -8, Top: -20, AllowLock: true, DrawLocks: false, Audio: "LockLarge", Pr
Fetish metal? Seems unnecessary

2021-09-04 20:25 UTC, ace-1331 commented on BondageClub/Screens/Inventory/ItemDevices/DollBox/DollBox.js
> +		if (C.IsInverted()) {
The inverted piece of code here is for the sign that gets inverted in tbe suspension pose. 
It doesnt need to be here(and would break the text if eventually, you could get suspended in boxes)

2021-09-04 20:25 UTC, ace-1331 commented on BondageClub/Screens/Inventory/ItemDevices/DollBox/DollBox.js
> +	const input1 = ElementCreateInput("WoodenSignText1", "text", DialogFocusItem.Property.Text, "22");
Can you rename the inputs to use the item's name for consistency?

2021-09-04 20:59 UTC, ace-1331 commented
Besides my comments, the rest looks ok.
This might be a personal preference, but I think it would be easier to navigate the color menu if the text and box colors were grouped up (like the fuck machine, transport jacket, etc). With Label + Custom text in the same color group and the rest of the box being in a box group, it would be easier to color everything quickly if you want the same color (and you could still fine tune within that group)

2021-09-04 21:07 UTC, Shiranui-Izayoi commented
> 
> 
> Besides my comments, the rest looks ok.
> This might be a personal preference, but I think it would be easier to navigate the color menu if the text and box colors were grouped up (like the fuck machine, transport jacket, etc). With Label + Custom text in the same color group and the rest of the box being in a box group, it would be easier to color everything quickly if you want the same color (and you could still fine tune within that group)

The reason everything has it's own colour is actually at the request of Titania she wanted the ability to have the custom text and label be colourable seprately. As for the box and cover being the same I will have to look up how the items that use it do so. But they do take very different colours current as shown in the default colours. And the heart is a bit picky with what works on it.

I am not sure really what to do with the colours due to that.

2021-09-04 21:08 UTC, Shiranui-Izayoi commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +			{ Name: "DollBox", Priority: 58, Fetish: ["Metal"], Value: 20, Difficulty: -2, SelfBondage: 1, Time: 1, RemoveTime: 1, Left: -8, Top: -20, AllowLock: true, DrawLocks: false, Audio: "LockLarge", Pr
Thanks I had missed those since I did that well in advance and just copied another item. And I wasn't sure with AllowEffect so left it in. Same for LayerVisibility. Will fix all those in a sec.

2021-09-04 21:09 UTC, Shiranui-Izayoi commented on BondageClub/Screens/Inventory/ItemDevices/DollBox/DollBox.js
> +	const input1 = ElementCreateInput("WoodenSignText1", "text", DialogFocusItem.Property.Text, "22");
Yes I will rename them all in a few seconds. I must have missed it when I did the find and replace.

2021-09-04 21:10 UTC, Shiranui-Izayoi commented on BondageClub/Screens/Inventory/ItemDevices/DollBox/DollBox.js
> +		if (C.IsInverted()) {
I actually left it in for the edge case of being able to be suspended via a strange item combo. Or if someone had console used on them. If it will break the text then I will remove it. Though considering it is an edge case I guess I can remove it anyway.

2021-09-04 21:21 UTC, ace-1331 commented
> The reason everything has it's own colour is actually at the request of Titania she wanted the ability to have the custom text and label be colourable seprately. As for the box and cover being the same I will have to look up how the items that use it do so. But they do take very different colours current as shown in the default colours. And the heart is a bit picky with what works on it.
> 
> I am not sure really what to do with the colours due to that.


I am talking about something like this: https://discord.com/channels/554377975714414605/721493158625804298/883447484972662804

You could still change each layer's color like right now, but at least you could quickly toggle the text to be one color (and the box too if it doesnt look bad, but it seemed alright when i tested earlier)
It's just a matter of defining a `ColorGroup` on the layers that are grouped up.

2021-09-04 21:24 UTC, Shiranui-Izayoi commented
> 
> 
> > The reason everything has it's own colour is actually at the request of Titania she wanted the ability to have the custom text and label be colourable seprately. As for the box and cover being the same I will have to look up how the items that use it do so. But they do take very different colours current as shown in the default colours. And the heart is a bit picky with what works on it.
> > I am not sure really what to do with the colours due to that.
> 
> I am talking about something like this: https://discord.com/channels/554377975714414605/721493158625804298/883447484972662804
> 
> You could still change each layer's color like right now, but at least you could quickly toggle the text to be one color (and the box too if it doesnt look bad, but it seemed alright when i tested earlier)
> It's just a matter of defining a `ColorGroup` on the layers that are grouped up.

Ow no I understand I just meant it would take a bit longer since it is late and I don't want to be figuring it out at this moment. I will do it tomorrow when I am more awake.

2021-09-04 21:26 UTC, ace-1331 requested changes

2021-09-04 21:26 UTC, ace-1331 commented on BondageClub/Screens/Inventory/ItemDevices/DollBox/DollBox.js
> +		ChatRoomPublishCustomAction("DollBoxChange", true, Dictionary);
`DollBoxChange` dialog is missing from the dialog file

2021-09-04 21:27 UTC, Shiranui-Izayoi commented on BondageClub/Screens/Inventory/ItemDevices/DollBox/DollBox.js
> +		ChatRoomPublishCustomAction("DollBoxChange", true, Dictionary);
Ow WHOOPS I will fix that tomorrow as well. It never came up in testing due to me not changing everything to DollBox. Yes Will get on that soon. My bad.

2021-09-05 11:19 UTC, Shiranui-Izayoi commented
I have made all requested changes to my knowledge. @ace-1331 can you look over to see if everything is working right and I didn't miss anything.

2021-09-05 19:02 UTC, ace-1331 approved these changes
looks like everything is there indeed

2021-09-08 14:19 UTC, Ben987 commented
Yes!  I'm curious to test this one.  Thanks a lot :)

2021-09-08 14:19 UTC, merged