Techno helmet
Ben987/Bondage-College pull request #2896
Opened 2021-09-05 04:53 UTC by Ayesha-678

Adds a techno helmet, and a hypnotic spiral background.

2021-09-05 04:59 UTC, ace-1331 submitted a review, later dismissed

2021-09-05 04:59 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +		        Layer: [
```suggestion
				Layer: [
```

2021-09-05 04:59 UTC, ace-1331 commented on BondageClub/Assets/Female3DCG/Female3DCG.js
> +				]
```suggestion
				]
```

2021-09-05 05:05 UTC, ace-1331 requested changes
- missing the HypnoSpiral layer name
- when in hypno mode, Im getting a missing asset error: TechnoHelmet1_HypnoticVisor.png  is it missing or should that layer have no image?

2021-09-07 12:48 UTC, Shiranui-Izayoi commented
Maybe make the helmet cover a bit more of the forehead. As I feel it exposes too much, causing it to look off a bit.

2021-09-08 14:26 UTC, Ben987 commented
Right on time for the next beta, we can always adjust the details later.  Thanks a lot!

2021-09-08 14:26 UTC, merged