Improvement: saved expression previews
Ben987/Bondage-College pull request #2904
Opened 2021-09-06 08:15 UTC by ace-1331

- changed the saved expression screen to display the saved expression in previews instead of just 1/2/3/4/5 to make it more user friendly
- improved the type definition and JSDoc of various functions/types related to the SavedExpressions and its menu

The previews are made to not include stuff that hides the face to prevent it from being useless when wearing masks. Here's the result:

![Capture](https://user-images.githubusercontent.com/59637973/132183592-22bb17d3-c336-43f7-b8cf-58965f0d02d1.PNG)

2021-09-06 18:01 UTC, Nina-1474 submitted a review, later dismissed

2021-09-06 18:01 UTC, Nina-1474 commented on BondageClub/Scripts/Dialog.js
> +	const ExcludedGroups = ["Hat", "Mask", "ClothAccessory", "Glasses"];
I'd favour showing Hat, ClothAccessory and Glasses since most of them don't block much of the expression, and maybe exclude ItemHead and ItemHood because most of those do.

2021-09-06 18:01 UTC, Nina-1474 commented on BondageClub/Scripts/Dialog.js
> +			BaseAppearance.forEach(A => InventoryWear(PreviewCharacter, A.Asset.Name, A.Asset.Group.Name, A.Color));
Rather than starting with BaseAppearance filtered by category then readding items, why not start with everything except the excluded groups and drop this line? 
Or you could even keep the category filter and just not add items back at all.

2021-09-06 18:01 UTC, Nina-1474 commented on BondageClub/Scripts/Dialog.js
> +	if (!DialogSavedExpressionPreviews || !DialogSavedExpressionPreviews.length)
If the player has no saved expressions, this is going to try building the menu on every draw. Should this also check `Player.SavedExpressions.length` or is the difference negligible?

2021-09-06 18:01 UTC, Nina-1474 commented on BondageClub/Scripts/Dialog.js
> +			MainCanvas.drawImage(PreviewCanvas, 0, 92 + (x * 170), 300, 190);
```suggestion
			MainCanvas.drawImage(PreviewCanvas, 20, 92 + (x * 170), 260, 190);
```
The expression previews are noticeably stretched horizontally. I think they look much better in the original ratio.

2021-09-06 19:30 UTC, ace-1331 commented on BondageClub/Scripts/Dialog.js
> +	if (!DialogSavedExpressionPreviews || !DialogSavedExpressionPreviews.length)
it is negligible, but to be safe & futureproof , I adjusted it accordingly

2021-09-06 19:34 UTC, ace-1331 commented on BondageClub/Scripts/Dialog.js
> +			BaseAppearance.forEach(A => InventoryWear(PreviewCharacter, A.Asset.Name, A.Asset.Group.Name, A.Color));
actually, there is a use for it because there is a lot of awkwardness with references when copying the appearance of a character. (and doing a deep clone is not possible due to circular references) 

Actually, I just thought of a better way so Ill include that in after re-testing to be 100% sure

2021-09-06 20:00 UTC, Nina-1474 requested changes

2021-09-06 20:00 UTC, Nina-1474 commented on BondageClub/Scripts/Dialog.js
> +	if (!DialogSavedExpressionPreviews || !DialogSavedExpressionPreviews.length || Player.SavedExpressions.some(expression => expression != null))
The menu build is now occurring every draw, in _both_ the saved expressions being empty and non-empty cases. I was thinking something more along the lines of:
```suggestion
	if (!DialogSavedExpressionPreviews || (!DialogSavedExpressionPreviews.length && Player.SavedExpressions.length))
```

2021-09-06 20:00 UTC, Nina-1474 commented on BondageClub/Scripts/Dialog.js
> +	const BaseAppearance = Player.Appearance.filter(A => A.Asset.Group.Category === "Appearance" && !ExcludedGroups.includes(A.Asset.Group.Name) &&  !A.Asset.Group.AllowExpression);
The previews aren't rendering properly for me anymore. I think it's because `CharacterSetFacialExpression()` needs the AllowExpression groups to be in Appearance and now they aren't.

2021-09-06 22:27 UTC, Nina-1474 submitted a review, later dismissed

2021-09-06 22:27 UTC, Nina-1474 commented on BondageClub/Scripts/Dialog.js
> +			if (MouseYIn(160 + (x * 180), 50)) {
The click and draw co-ordinates are misaligned. One has * 170 and the other * 180.

2021-09-06 23:08 UTC, Nina-1474 approved these changes

2021-09-08 14:28 UTC, Ben987 commented
That's a nice concept, I'm curious to test it.  Thanks!

2021-09-08 14:28 UTC, merged