Overhaul image caching
Ben987/Bondage-College pull request #2987
Opened 2021-09-20 00:47 UTC by zorgjbe

I've been investigating the memory usage of the game, and as a figure, right now my Chrome GPU process sits around ~1.16GB. Running this: `GLDrawCanvas.GL.textureCache.clear(); GLDrawResetCanvas()` gets it down to ~350Mb.

This PR consolidates the caching done in `DrawLoadImage` and `GLDrawLoadImage` to a shared cache, and also move the texture cache inline with each cached image. Also adds more retries with exponential backoff (since that was what I was looking at before seeing the two caches), so an image failing to load because of a transient issue should get retried (search for `backoff` in `ImageCache.js` for its calculation).

Notes/bugs/possible enhancements:
- I haven't actually tested it in the face of an error, so it might be buggy if that happens. I know it can display the login screen, and chatrooms.
- I got a bit confused as to why the Drawing cache would behave differently from the one in GLDraw w.r.t to "Assets". I've removed that. The only leftover is `CachedImage.IsAsset()`.
- [ ] The code triggering a redraw after a load completes looks wrong to me now (the `loaded == total`). This is why there's an unused `loadCallback` parameter, but I wanted a POC first.
- [ ] It seems there's an issue if you toggle the aliasing on and off. You end up drawing black squares, and `WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context` (GLDraw.js:401). A quick `GLDrawResetCanvas()` fixes it.
- [ ] A time-based eviction mechanism would be good.

2021-10-02 17:12 UTC, elliesec requested changes
A handful of minor comments/questions, but otherwise looks good - about to pull it down and give it a try.

2021-10-02 17:12 UTC, elliesec commented on BondageClub/Scripts/ImageCache.js
> +	 * @param {ImageCache} cache - The cache holding the image
I think this type should be `ImageCacheClass`
```suggestion
	 * @param {ImageCacheClass} cache - The cache holding the image
```

2021-10-02 17:12 UTC, elliesec commented on BondageClub/Scripts/ImageCache.js
> +		});
I'd drop the `this` aliasing completely and just use arrows in the callback. Similarly for the listener below.
```suggestion
		this.element.addEventListener("load", () => {
			this.errorCount = 0;
			this.state = CachedImageState.LOADED;
			this.cache._imageStateDidChange(image);
		});
```

2021-10-02 17:12 UTC, elliesec commented on BondageClub/Scripts/ImageCache.js
> +	 * @returns {CachedImage?} The cached image, or null
This doesn't look like it ever returns `null` (or `undefined` for that matter, which is what the `Map.prototype.get` call would return without the provided key). Either the type notation should be `CachedImage | undefined`, or it should just be `CachedImage` (I suspect the former?)
```suggestion
	 * @returns {CachedImage} The cached image
```

2021-10-02 17:12 UTC, elliesec commented on BondageClub/Scripts/ImageCache.js
> +		}
Could simplify this a little:
```suggestion
		let realImage = image;
		if (image instanceof HTMLCanvasElement) {
			realImage = new Image();
			realImage.src = image.toDataURL();
		}
```

2021-10-02 17:21 UTC, zorgjbe commented on BondageClub/Scripts/ImageCache.js
> +				let backoff = (10 * Math.max(image.errorCount - 2, 0)) * 1000;
True, I made it more linear in the end, because I couldn't find a formula that wouldn't wander into crazy long times after a while. Arguably, I could remove the `- 2` to make it start backing off sooner; right now it does 3 bursts before backing off (as the previous code did).

2021-10-02 17:24 UTC, zorgjbe commented on BondageClub/Scripts/ImageCache.js
> +		var image = this.cache.get(url);
Oh, it's `let` for "can change" and `const` for "cannot change", and `var` is the old keyword? I messed up those because of Swift. Will adapt, then, thanks for the hint!

2021-10-02 17:25 UTC, zorgjbe commented on BondageClub/Scripts/ImageCache.js
> +		});
I think I checked, and `this` wasn't the correct object (`window`, IIRC), hence the "weak" reference. I'll check again and fix if needed.

2021-10-02 17:27 UTC, zorgjbe commented on BondageClub/Scripts/ImageCache.js
> +	 * @returns {CachedImage?} The cached image, or null
Yep, came from a previous iteration where you could ask the cache for an object without loading it (had a `load(url)` method). That didn't seem helpful, so both methods got merged.

2021-10-02 18:17 UTC, Nina-1474 commented on BondageClub/Scripts/ImageCache.js
> +				let backoff = (10 * Math.max(image.errorCount - 2, 0)) * 1000;
#2987 implemented a backoff concept using hardcoded times that's been merged into master already. You could always have something similar to that.

2021-10-02 18:49 UTC, elliesec commented on BondageClub/Scripts/ImageCache.js
> +		});
`this` won't be the correct object if you pass the callback in as a `function` (i.e. `function() {}`, since functions have their own scope. But if you pass the callback in as an arrow function, as arrows inherit the ambient scope. So:
```js
const outsideThis = this;

// This function won't have access to this
const func = function() {
    this === outsideThis; // false
}

// But this function will
const arrow = () => {
    this === outsideThis; // true
}
```

2021-10-02 18:51 UTC, elliesec commented on BondageClub/Scripts/ImageCache.js
> +		var image = this.cache.get(url);
Yep, correct - `var` is the outdated one. `let` for variables and `const` for constants are generally the modern ways of doing things.

2021-10-02 20:17 UTC, zorgjbe commented on BondageClub/Scripts/ImageCache.js
> +		}
I did that because the (my? I'm using Atom) linter sees that a straight `let realImage = image` assignment could still be both types after the type check, and gives me a warning for it on `img.setElement(realImage)`. Arguably, the linter seems too clever for its own good 😉.

2021-10-02 20:28 UTC, zorgjbe commented on BondageClub/Scripts/ImageCache.js
> +				let backoff = (10 * Math.max(image.errorCount - 2, 0)) * 1000;
Switched to the simpler array method.

2021-10-02 20:28 UTC, zorgjbe commented on BondageClub/Scripts/ImageCache.js
> +		});
Fixed, thanks for the pointer ❤️

2021-10-02 20:33 UTC, zorgjbe commented
Okay, review comments fixed. As a heads up, I suspect something fishy is going on in b2d72b42b74a195023e0b03d007bebdf3a5d090a, because I'm seeing 404 errors on that PR branch, but if I rebase all of it on top of 82f6486237 there's none. The code seems to try to load assets without the size in (so no `_Large` etc.).

2021-10-02 20:44 UTC, elliesec commented on BondageClub/Scripts/ImageCache.js
> +		}
Ah, I see. That'll be the passive type-checking in your IDE rather than the linter, but same effect. Happy to leave that as is in that case - it's not hurting anyone.

2021-10-02 20:51 UTC, Jomshir98 commented on BondageClub/Scripts/ImageCache.js
> +		}
@zorgjbe You can add the type manually above the variable:
```ts
/** @type {HTMLCanvasElement | Image} */
let realImage = image;
```
*(not sure if those exact types are what you want)*

2021-10-02 21:56 UTC, zorgjbe commented
I added the time-based eviction on top of it, and tested the backoff by yanking my webserver from under it. Seemed to work fine.

2022-02-17 16:12 UTC, zorgjbe commented
Updated, and fixed a couple more issues. It's working great, with the only caveat that it has a tendency to fire up my laptop's fans when I run that, so there might be some performance issue in there, and I don't have the tools to really debug it, so if someone with better graphics stack knowledge could help, that would be great.

2022-04-04 13:55 UTC, zorgjbe commented
Okay, this one is good to go, and I've gave it a spin by roaming around in the club with it. Sorry it got a bit out of hand commit-wise.

I don't think I'll tackle implementing a better refresh mechanism for now, since I'm not even sure it's possible to cause a redraw from only one group (I'd take out the duplicate CanvasBlink as a first performance step anyway 😆).

2022-06-05 15:07 UTC, Ben987 commented
Alright!  It's time to test this big one.  I'm curious to see how the game will react.  Thanks a lot for your hard work :)

2022-06-05 15:07 UTC, merged