Misc: Code restructure.
Ben987/Bondage-College pull request #3308
Opened 2022-04-07 08:35 UTC by remiliacn

### What is this change

This change is more a refactoring code to improve the code structure. In case of new languages garbling checks that is needed to be added, the new functions added in this commit should help to improve the code's maintainability and readability.
This change has two main goals:
* Make the if statements more readable by using `indexOf()` feature instead of using nested if or statement.
* Group same checks to a function to improve readability and maintainability.

### Testing
Local testing with several string tests are conducted. The below are the functions that used to test:
```
const testString = 'abcdefghijklmnopqrstuvwyz123456789áàãâéèêíìîõóòôúùûçñaeиоуюляcйхжклрузсгйбрвыдфгнм';
> SpeechGarbleByGagLevel(21, testString, true)
'm   m   m   mmm   mm     mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm mmmmmmmmmmmmmmmmmmmm'

> SpeechGarbleByGagLevel(17, testString, true)
'm mmm  mm  mmmm  mmmm    mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm'

> SpeechGarbleByGagLevel(15, testString, true)
'mmmmmmmmm  mmmmm mmmm mm mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm'

> SpeechGarbleByGagLevel(8, testString, true)
'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm'

> SpeechGarbleByGagLevel(7, testString, true)
'eebmкmeemmheaaammemmahmemmeheeeeeeeeeeeeeeeeeheeeeeeeaeeaemккгкaaeaaфeaгггмкгфaфффммгммм'

> SpeechGarbleByGagLevel(6, testString, true)
'eefkкmeemmheaaammefkaheefaeheeeeeeeeeeeeeeeeehmeeeeeeeaeeaekккгкaaeaaфeaгггмкгфaфффммгммм'

> SpeechGarbleByGagLevel(5, testString, true)
'aefkкmeemmheakamnefkaheefaeheeeeeeeeeeeeeeeeehmaeeeeeeaeeaekккгкaaeaaфeaгггмкгфaфффммгммм'

> SpeechGarbleByGagLevel(4, testString, true)
'aeememnhiakamnofkaheueaahaaaeeeiiiooouuusnaeаахeкакаафахкнфыаффыамфымкн'

> SpeechGarbleByGagLevel(3, testString, true)
'aeemefhhiakamnofkaseueaasaaaeeeiiiooouuusnaeаахeкакаафахкнфыаффыамфымкн'

> SpeechGarbleByGagLevel(2, testString, true)
'abemehnmhikmnofpkzeuvwysaaaeeeiiiooouuusnaeиоaaeккaрcзмкркaмкммнмм'

> SpeechGarbleByGagLevel(1, testString, true)
'abkmefmhiakamnopkaseuvwyzaaaeeeiiiooouuusnaeиоaakккaрcзмкркaмкммнмм'

> SpeechGarbleByGagLevel(0, testString, true)
'abcdefghijklmnopqrstuvwyz123456789áàãâéèêíìîõóòôúùûçñaeиоуюляcйхжклрузсгйбрвыдфгнм'

> SpeechGarbleByGagLevel(0, testString, true) === testString
true

```

2022-04-07 09:26 UTC, Jomshir98 requested changes

2022-04-07 09:26 UTC, Jomshir98 commented on BondageClub/Scripts/Speech.js
> +}
The argument about IE browser compatibility is not valid, as we use soooo many different features (some of which don't even have easy equivalent to transpile manually to - like `async` functions) that already aren't supported by IE - IE is just not supported in BC.
Also we heavily use `includes` in the code already so no point not using it here.

2022-04-07 09:26 UTC, Jomshir98 commented on BondageClub/Scripts/Speech.js
> +				if (H.match('[a-z]') || dialogContainsCharacter(" '?!.,", H)) NS += H;
Honestly... why not just use regexes for everything? It would look much cleaner and you don't need any extra functions...
```suggestion
				if (/[a-z '?!.,]/.test(H)) NS += H;
```

2022-04-07 09:33 UTC, remiliacn commented on BondageClub/Scripts/Speech.js
> +}
Sounds good, In that case, the mozilla doc might be outdated then.

2022-04-07 09:38 UTC, remiliacn commented on BondageClub/Scripts/Speech.js
> +				if (H.match('[a-z]') || dialogContainsCharacter(" '?!.,", H)) NS += H;
But definitely let me know what you think. In general, If we want to replace all of the if statements that using includes with the regex, as stated in the previous comment, the string that we want to look for is not always be consistent, that means, regex needs to be compiled multiple times during a chat room session. This may cause a significant performance impact especially for older PCs.

2022-04-07 09:39 UTC, remiliacn commented on BondageClub/Scripts/Speech.js
> +				if (H.match('[a-z]') || dialogContainsCharacter(" '?!.,", H)) NS += H;
Sorry I think I mis-read the comment lol. Nice catch.

2022-04-07 09:41 UTC, Sidiousious commented on BondageClub/Scripts/Speech.js
> +}
I believe old Edge support is still relevant, but `includes` is supported there too. Async/await is not, but it's only used in the chess minigame and would only break that one screen.

2022-04-07 09:55 UTC, remiliacn commented
This force push revision above contains the fix of the two comments above.

2022-04-07 10:07 UTC, remiliacn commented
The force push revision about removed comments of why used `indexOf()` instead of `includes()` since we decided to stick with `includes()`

2022-04-07 12:39 UTC, Jomshir98 commented
In this case, why not just directly use includes instead of the indirection?
```
dialogContainsCharacter(' .?!~-', character)
```
vs
```
' .?!~-'.includes(character)
```
Also some of the functions don't have annotated the actual type of return, should be `@returns {boolean}`

2022-04-07 15:25 UTC, remiliacn commented
Revision above addressed the comment made by Jomshir98@

2022-04-07 15:43 UTC, zorgjbe reviewed
A couple small comments, and thanks for the refactor work.

The only major surgery I'd do would be to hoist the for-loop/parenthesis-detection handling at the top-level, and sink the GagLevel checks and substitution inside it, instead of having a repeated for-loop for each level.

2022-04-07 15:43 UTC, zorgjbe commented on BondageClub/Scripts/Speech.js
> +			if (Par) NS = NS += CD.charAt(L);
Duplicate assignment here.

2022-04-07 15:43 UTC, zorgjbe commented on BondageClub/Scripts/Speech.js
> +				if ('úûùü'.includes(H)) NS += 'u';
I'd move that block to a helper too, say `stripDiacriticsFromCharacter(char: string) => string | false` or something, since that's repeated a couple of times in various gag levels. Then it becomes
```js
if ((strip = stripDiacriticsFromCharacter(H)) NS += strip;
```

2022-04-07 15:45 UTC, remiliacn commented on BondageClub/Scripts/Speech.js
> +			if (Par) NS = NS += CD.charAt(L);
Nice catch.

2022-04-07 17:08 UTC, remiliacn commented
Two above force push was to address @zorgjbe comments.

* Add stripDiacriticsFromCharacter() to strip out the dialects from the character
* Move the for loop to the top level to make the code tidy.

2022-04-08 19:19 UTC, Ben987 commented
Thanks for that one.  Are you 100% sure it doesn't change anything for the in-game experience?  Cheers.

2022-04-08 19:21 UTC, remiliacn commented
> Thanks for that one. Are you 100% sure it doesn't change anything for the in-game experience? Cheers.

I have tested using different gagEffect levels to make sure that from 0 - 21, the garbled text is displayed as expected for each if check. So there should be no in-game experience changed.

2022-04-08 21:37 UTC, Ben987 commented
Very well, let's test it in the next beta.  Thanks again!

2022-04-08 21:37 UTC, merged

2022-04-08 22:11 UTC, Ben987 commented
There seems to be a small bug in your change.  The right parentheses are missing.  For example:  (test) shows (test

Can you fix it?   Thanks.

2022-04-08 22:13 UTC, remiliacn commented
Sure I will look into it.

2022-04-09 02:38 UTC, remiliacn commented
#3312